credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              id: "39c19e12-311b-4dd8-b402-a2c3f062ee5e"
              privateKeySource:
                directEntry:
                  privateKey: "-----BEGIN RSA PRIVATE KEY-----
MIIJKAIBAAKCAgEAyS+rNKhH2bNOSLOtFCCOt6T+7xOtZEDDCqxtJwKaBvAQUCJw
9y8+NXr3KT4gGeUzazI1byArb17ZkVhXUbUZYp2XrcSdSuuaCZm6kmSPIP4wCXzf
WzjcP3/WFaw36AgrF1Ft5crywjHqc/vLXfkxSnlS9HJRREaAoCns3PkzsYFxesF2
+SkrfP8TueLgnmPZvQMjalcpYsl/VRWDIr4FNfId94lpR8aZ6oohLuDKBUlmXA0e
wyR/LcuP+cXaf3SiM4vF/33pmFAj5AEv+kI70qfqzgKUfxOwYobflHEJMiQ+8DpC
ifXxRZT4tfKINfsKJlSA4oRY6jExnPmzV0oLE29+T/n2NhGJNEJkbubMA4l9Qgkq
AKhAICA+ZBCY1CB1d3SShem1xWQmtUGREeddFIwMHDg5Svz2/vrPzRZz/19FMk4e
iRnnL3P+NNYeUvIZ6d8mmH1YwrGqBC0TKhyjfsXkaWA0Qjjlu7W8w9W4jrMiTpYc
WbnE05RXjpHm3hY6lqRsU5RshFwE1TKbzEB72xUq8uL9YsC4TtPrWymqFqO1OmXF
QSfRfLgIY1yORv7tf7Z8u8UeK10mSUFDgMCtnLxP4pvF+wg+AdWb30y1foDjZRxZ
NQb1w4Pm8FGTW1pa5cYqYJj2qNZPxPXL50L5SLg2rYcEYB4/XhosSyaRGaMCAwEA
AQKCAgAFIGfWcatTCtSl2Z5Bcwrv9w5f/Tpf4Z6WuQoXAmP2ZUulHxuN0PBe4IFH
1cNvpX2H78GY0VMKBXq5z2x6MokxEB77WJVBgXttXzN344QaLSAAPeRbKLnEDHfi
GX9bNEoU0Ahi4KcK98anqfTmsiDlau4IOJmFid5hNnBIuTjt/wRrQl7LvpbTGpTg
Gb3ri1PTEy9l2E6/q67I9kFfM0RiuYa19hRutcraRSbPUP8U32fyVItCIb3z5soG
bVpCATDY62jiN80qCnC/sKAOWn23wnujQEGUc2X9PL6Zw7+ePXo1GOb1KQU65q7n
xARgi8MYcvLN0t2JKjO/ckV1pfdePcyB3dA0XsgH8Mw6nw9q8x/c9qvaL7ZefwjO
6zWVD+gO26sr/7AwHndWI+qj8ZI+YC4HHEu1JBdB/XMW2XZYqgqaGI1mp3uor6c5
a4YJlK9IgtLsocqkHn6klJHamvMxtuItv9cAlygsOyjNNO8+gKGIiULF58iMwm2E
htcXBo0am1B/28Geg+yQpgv3vvXDfTzbERWjrhtNLBlS6ukSANSXTnaoCgKzsp02
/zmt7KX4n9mjf/VwSzP8NEksGl+Yj01hBV6PPnTVZrsT3Wgzqxl6OxclO6aYGVao
D2yoHgmlEOZodyqIZRc7+3TE5oBihD6NxDz7C3HkxHz3vYw8MQKCAQEA+dCg5nBa
3fLT836JuavZw1Xtwg5Yb2SG4LLh9WhL7rjaj8gH/lcG9ppal8mtIY6iR7DbjxwQ
Sd6Ogg5mEU73XM5bbWHV9bCcrq8SVbTV8ehbSD5sbdCouXkpGtjKXdHJyFhJUs2Z
ZUGza3JpRLzO2n5XMZvKYAHXv5g3xnTqRHrAhCCdFn1nTkRT9uynCnEqiISRmNDt
NqqP6u3PWEYnyfK/o37PafOGBbqKRlcnbkbDDHNvfH7F1GSCnrd47f8X5u68IvPM
VWYR1lRwbYzvONTqlyCNijKZzF9waloro53ECrQcgkLKNixLlm3mCgtpyelmPLBX
fIs8w4BPuvJ4XwKCAQEAzirSl1gljQybqLO0Ozj+xM18W9S0PueGBlHgiEH3QdBs
frFnGaLV71FlghwIdSU381sOBjDv7F23L1DW1vkrg6ZW2q636UztoDnQ1bnzigZz
l+nJ19giYTu6YxmyGBERkVaunMS3Nj6lXXJ15JzLNYfjV7s+8IhXqD/1jURKo29V
S6lZQBVlK/A+nCoeUu+kIeei6JIg9dJg4T/rb+XJJ9klXbhq5P8eqFp6SLLO4emv
M6dKMwSIFISMpgPYraF/yloMmpwhDZTRGUP4JfhCveq16UOkTKebxwymhU/xrUVk
ypC6zZT4vj2tFHHg1gLehx/m5pKv9nv+BcYBx5l1PQKCAQEA4URRIxsjxUqH9+Ue
GnCt4GfnCvtWobQbsBl+ioYvGqhUZh0xoBcn703G7WLuHPl6unzvr7/VrFblWL/V
KDx18JkgdqUng/Jrh1XVibWUyxwE3EN2ERx8WSu5dj0RVsKrW17JV8KQVW+GdBhq
dpJvUTVmORTLzAE9ZMbFXM7mxTOP0FV8ceBJPJl+wYYrJs5fVVV92Thk/8uUFXu2
Ylp43LFqP+tE67yuGRJaSA2lP9rNXbfmS3QhvmGYK7k0ciB6lEKpIjeIBWYSJZxk
+VSCD1Rn6jlviLQSXemd/DktatAEDMbXglrp7ynIS3D0ZBBgp7Mw/v7hFSyVcZGN
0/17rwKCAQBSRpCoSUsjEQcFukGQ6NvzWjXox+fuuqKn3wEGH503LKA/pziH6I4L
5aXm2J0fcuzzN0FPgzQcVgIG5fH29JVDApzixJsshcDHEoue34iraouy8l/UvbJq
r1Vgux5xsE4cfEVO1spu4W1I76bQxynpgQNfPaCOiTrCMFQkPj6zHnkhqsGta1xm
voed9skHPA96YGCJA9gXgg+blNC2ZTNzrZrV3gT6wj1P3luyq3kYexOqP3bDCWnt
FkCy+BH+qNbAwFMLWIdwThVsSc28CWlJNWPHZXEqDjGCrC/AP/koturUVBHYfT0P
Xrm10QRzI83+iuKw3ZVPfogPccfACiPZAoIBAHUup+AasHxLuPft4Moc0ONVWYby
nSUcElIhlyftta47l/O+THqmI2NYKgdyCmgmq747z3Yv8qC2h9UXxcd/TBZjKo15
w86ToGcU1/bj9Jve0k7Vyrv2MGLuVi80Nk6pKGhx3zx4islZHDzQkMDmctd8Rg8N
sucEjJXSHzvQCtL4WIPd27lG711UAPnyAwb32pVW3Y7nnmwbwo+sRzP0mEB/gPhM
KkM7h1U7khUt5iVUqo4q+NWkQ31dgMbGHbnvoDFsBPT4/6kkXCr3egBrMf4yghIA
f5/Q3Of5XGE06mh2g4K2ktUzZTx04jmTn908xhZG6cOm4dBUD+mzA+T1BBc=
-----END RSA PRIVATE KEY-----"
              scope: GLOBAL
              username: "git"
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: false
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  defaultFolderConfiguration:
    healthMetrics:
      - worstChildHealthMetric:
          recursive: true
  extendedEmailPublisher:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: 0
    precedenceBulk: false
    useSsl: false
    watchingEnabled: false
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:8080/github-webhook/"
  gitSCM:
    createAccountBasedOnEmail: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  location:
    adminAddress: "Endereço ainda não configurado <nobody@nowhere>"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  timestamperConfig:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
