credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              id: "39c19e12-311b-4dd8-b402-a2c3f062ee5e"
              privateKeySource:
                directEntry:
                  privateKey: "{AQAAABAAAAywlRPv3H1aWDJsRoc+bPiiAdzjcXvJZjEJsr7aWhpOsoIrtXIgZxuKWOG3eJ0r8teI9h8VYsjYfbqwtWkydOJBtBsygNGxEUxxZZnbPxEeSkhkLwbY5OFU3L8UGSgNtFSqtB/HDbkkp3m6yt09IMwIx21wE4zccciNzwiFrUsWa3rL7qAXiqhBAIW0wbfyy7BI6heVk+ygs4EKXa4aZ/GFzgrbV/d1PwMsPT4ZgewMzD2znERa6ECCI+U14pOpTtokRUPgW+AOvsTghAiYFZY8k/CosDitpCzHwiWkIoNPxWEaPvlEolgJX/OqCYeBAHH5mHU34eJa1hbkLzWoe02crtoeaC9yHWFSrwx2ekchfnrhEdsn6YY0nXoTzuGyxvYhCZSigOUgwkv/6p3Y/c/Q2GVnvo0ASBSpQoD2moaubNZtAT0+a3mgVN2KNmiOVSg0PjDTPjdlGAU8dLDur9TBnCUVVhcXwOxyLzxXdGnwjpBVXdd3zhuGJfdRVRol/vT59nzShHRJso5Rz5G0yCrqvVowx6YfTuIE4bw2pawO5cX9NyndA7VqHD5Bb+/j5FNM2eCBp5vD184+DSHvqmoksu8tfVruVRoTUI79MvDvDnmSAdm7TMFVjoS0qSXjoSfmt+Xz3EQT5zPSsorosX/YJ16lX5vbI9u64BOaEgY95ExgRS/StWtAoDVTqp9GzMmtnX6e9Ub/puPaJx1lAfnxFUu/EK1zfT0A7A2mF4iavPLNZ6VQR2rRZhc3Kzh4oD5LCEcPOelPehroIh7P/9ZXsUL6CNWtskZ+ymKLF85jDd+od3/MTcEbU6P3Yewdc6jwHPA++JzF8nfDsrcPm8z9W9YQFf3uCZFigw3EmRqFJiiaR9QnfS8i1D9hY5sRbf50GID14CNZCcwS9fPws+cJl0faL5Jc7I5xzaMtogiwglfImtW6F6IXr2qZdTapdIJFWu5tlIpBT+7L8sAtWUieKwUE1j+avOStfphXm1Wup751i0/KByXezC91N+xAU1gSUsYD1Q01dptwEzcOxkTTMJS/iF+5YaU9dv8L3jELfdmuE+2zl5BDL0Ze8pte5wY2tKprvXKrvMQ+2QaGSA5gS1vI1vdDoDk4GLDpAozajlatH+9I5CfbBtdFfbfc0Hj8BZcjTvNZeeTxb0y3m2yxsjuja6BZ0XAP2am000OaYymgxGqczcMP6jjqKNqsfjnHHv/yw0pWw6htboufdvLCxn3XWGGQRlm7YVi8pofSekY0tDilY8IsS8eWvVMiy7ofUOGAtiY5k3KAtJBok3bT8xg3gxtGMb48HEfPkX6OS7sBB95NCVxdq8b6cAWXkywR8ifQDslTDu9eh8g9h9JMkqnWqIoisS7P5HGjaTR25qkrHQOkIsTpR9tYGLa7UWEbKSSFusm6KfgTXDAQF90UcEqYVVsMawIK2NqJBILtQEB2xoHHC1ZNf8O2O9VY/yabjYJzYSWezl8o1zgMC/180Sq9+dYDR13FpCrOyfgoUFtxCPnQFEcl/KzRubUY7uelXyfPsA1s0ulTAaYB5VSuBiD6qw2nRmoi7UnaRALCAnHZuAcXd5Sma7LkZOOA9JMMkSSblKbFYdVygbZcOCdFLMaQHEvbcjNlOm48Elya3ht/qqeAIoMxOR5ZdbGSNtCZJ7Fxgz7EAbPfMmKcufb4sEP0QnPPT8N3YPmB+QMdDGeNlKAJLC5rQwf5Ea/IQ0dwqOUtiB0gL3a+nyLXGeBmvk7OoK1EEXxYVh6iWv0v/xf4aL+QPFvtDQmHt8ELJYhxuMfB1BKPisETUff1taTVKIN3zHcEfMdA6sLjO2kJpIvA/6NkjtTdjb1cHOMsANk8sb0eLYu1Tfocxqm2yQoBTrzR9Vem8NfSUpfL+HEFjfUICUztK4Sr+2g0q55/rum61Crkw3w+2T25fnYApyOABNRpxE+omQ82f/avZ9EoJz6weVBseUqBi+8xSTnYb81A6nVwH6oFvjHZBhAprqC7PaMIfiGgG4q4v4/z/0YYK+tEFZD1vn/zAVSGK6oFBD6m5yRoLsn075iw7Wy4FP4rC1gFedSe7/bfedhXuptbUfc77YULllEMaGM6NOtIMMAKbbhk6WjKPz4UrMK6Q1/NhrG0mDLHbxW7UR579pI86r0QL2O20Vk0MHArDg4lKTmlicZU6hzT3EqoRRXFLykGQXH/dOvWej7uv6tlamUacT+0mMhsKNgc0JLyi+GiE1aRrg7CnKm/qFYBiOwm8zjE8eb8pf+k7LluUycbPYhgruQjt+B5XEWIjEdy5J5O/GISrP0wM6bi6J1FNzzuS6nNgF/z/YwbWgnryHiJ7u1QOtYqDSOpSawmVk5AmotYW5Bv2i+oUaF7WkazSR2H5q5pWl/Xvpq9qnnqv0U1yGanQeD1sPNiHE0OUVVmDaa7V4vnemXV7LUpwhl/0LRhKrQh+aWyleCMkkZxFszmRAQVKCF3sz3OD7NpcntgdCvhNUN1LzvJQ+hl8JS/YI0kOjdJ01S8EmsptSTMXAkEhIoUrP3SIqrZexdjpHWcZI03putfIZ+LIXcnJ0icqwb9A/hqHR5hD5hvn4V5m4s6KiVsx/Nxj9WLwfHH++9DdQmz+ntggLLxscHX4wN6FoMeblZwO/ZlIlqkrKcon71I/jLBwWZViyoLnP+7BpVAcheSAF7zJGmNm3jVbPlJtsIHne/ilZEZLWabEvj88GiZHAotsV3CTbfB39MMDLPJOXY0g+CBz5BxZn2pRU5tEcjzqN9cSrTb6upb8MkUkUBjr5IqKgHh4ZP8YwBu60z147YLGUvvFEp9pAyHuNw/LnCn9N2xHgcUFAi9X3eNhiR+yvyL3dHigUIyN2av3T85Pmh1HoWogvZcUg4NBgOI16fFsFbrqg6EgWxImj+2jKl0vcJpaD0cuanLTqbNeHp57MRADYsL/I2fmTSy9J2fxO/2Mx4zkG6utwaxtbqhhYqeQvUiWHX3CaEVZLrWWrSoyUBDnIcpzNQEI+TqLGLNOfKlbRlCg0Uj3dF3ZUhA1M5mAsyLC4SsacztEPznKXcR4SI5dwnRQJFVoWR7TmbTAHv/RTUzfEiY8jF76MU8x3jd5ap18IM+nw7lNQXFYgjuNZrFauPQtE+Uc3rN4T2rGTEiRSyQfLYyEMO7mB38KiHazid3yhfW8y0/5AEHd6XX7+LCKfHzP8r6MyodcDr66oqvLmqLzhKRPGJcLK94miscbXlJkqgxsigQLfwV6azvnOLkdLckjBMs8YxKlKsC/zEOIiiiOKI5cBOPedV7k+qjzUvRNXw/PTnbTDroSZoKkW3s00lZL896WhiJwB+ln7sAVsp62IUgdHg0dQ44CvMiK+29kuQaUGx2z+NJlrhxtJzxX6faly6sDdgM3uTlBCX5mCYEyt91NbHqxU1JXDFuPCxtjDLhZvrdTkv1ltwEuS4BMBATlcaiXZ1xa07+yQUC57bsgmPbfOU9IVMIqiAjAX4mLLEpZWEXOfTJqXXV7YFtllLJXVcbEjO0v9izJYbuODzqKyea4KA1WFXF2RoPpaNQ9fvqQTm1Wi4FbBFIPqgwzpc9xdtDxy6AYygei/hGPgZC96+kZhsr5CBWePA/7U0cDE02v3Y8lbkjJ/7SkL5NWFlI4D2Z2I8/HlYRCXTm1DW8NX5mhvBu6RSiBIDibdyene4LaU3n9C54JTQ6nekPrIwLRJgoiyxfhpOh6UXj11yqVJXKwn0CChgRu0fMSFrdf0jM0rUWpn4rfzAWIHoZcPpp0U5K6vXUuJwMDurQMFDeYt+G2ZPylNw+W2MNk9yF7PZvGBpfYXOx/kyPavosEiZCMkI5YZpM9k+NoP7fy+ymzk8QSaQP16WXgn8QUs7yIvT0maPbRE/NFClcISKXOjRkAf3wxK6MC8FVyQKErME0fqwnNPTgfJ9m0pMeSf8PBJH9SYgNsWu8iajSqKao972+31p8Re7gn1RzVhitvoET/03y0v9zdr+YQutyuxXQ1CaY1VN+LitalQt9xk1SrexuLsKD7GctU2NVVMehRSzfExRUsLMA8zVT5/+H7kuN7L7lGVGHdGE8E8U4NMs95wjCdcqOrWSnKGUcmDkHxs3xaPJCYDs2xBRe+szV+HCGFsZNWMfBHo0G5OJbMn7q6liprhtemisOmJUrdnNJRMnmR/0Rvp0HfK4WKgJIT/ZKcW3knqtQr6pmdXq4yG3d3dNEL2++eCfXPdhuhjAeKZ+IQe7gfdpc7dQq7uS+Sx6Gkhn8qZfr56t6ipJwCl3ma/cgEOdy/ryBDxcTNYHqSKOmLdzqF08tG2S2/6lV0T09Dc/iHI2Ote23PtMmFwnvUc2B}"
              scope: GLOBAL
              username: "git"
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: false
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  defaultFolderConfiguration:
    healthMetrics:
      - worstChildHealthMetric:
          recursive: true
  extendedEmailPublisher:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: 0
    precedenceBulk: false
    useSsl: false
    watchingEnabled: false
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:8080/github-webhook/"
  gitSCM:
    createAccountBasedOnEmail: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  location:
    adminAddress: "Endereço ainda não configurado <nobody@nowhere>"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  timestamperConfig:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
