credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              id: "39c19e12-311b-4dd8-b402-a2c3f062ee5e"
              privateKeySource:
                directEntry:
                  privateKey: "{AQAAABAAABEQdLw+GfEvq4C4ccnofglDtd1FTTEWeUzZVau0NZSZzOGEvhcreUIGQC40xS6TWYe/xfZZe/zB39c/EQ11Kqn7XQk7ZmvuhM4uIQwvgQRj7Z/vSQ61NNO5Bbyf96mVj4odVNErk6dh3odj2keOrS9jUK9EtElgYXal3bYG3AbSHFzrxZLKW9wZguuq5OlnF0ZLlgbKv0ihPubCAWy/nnfSEGGsVsxfU4Yk/zI+kuI2e1gGvyJISr/4J/ossTJIeVBV9UgNpYZDn+PvwJFAiMyGCKytnYwSII7xAum554H3tZTfidR8t+gjrTWAGYg7/riIMsujsSBYs9ytv1QHDwNj4z+pLmx/FWnYWRW9BL/at19S3EoKQkB6+EZWf0/gyZk3pR1DVP0iFyr/v1mPyIMYvu43yTLmeaII1LhkwXzINKwbXplwDSOtkbF4cgh0AyHng4rq9TAO9NYEBV4EFA99nVv/u8K2Kc+IAusl+gAjoWrVKfuUpcRLSz7crs1m4lQMYSYgAHfdOVe4eFXHeXcNNDOPJYt4csfMiMDdhquaet/BFLVFzZoiHGbCXC+ea7CZKiBkzdv4AcwjDDPvnF1X4HnYgVOI4wG1bim/9JzPqV3m5kmJi6ug/yLksKUN0TDv90sjqIe0rP5BdS8O1F9mkug/eUXigOMqoZMM36Yg10hyDU54USXT0OA3AnT1paNi2lGzD2X72jNo6LlZH4oPHsydHhBH4yvZsXCR5z2Yh3zRmL+QSHhTQKd7Uxm4R/+cK1nvgt2wYa0UgR77uqUuzGhRnG3IEOHCkMPebQb5/SGuC9/e6Re1royPS+xE/gSHKG1lWvRZslOFep3RY3y0cIseWM9DwYjsagoBAvYjPALDPTZpohVqTKO9Pcp1hKBHDBFb/m6tWG+otuhQLHLlT43/3esXbJIYYnKL82mxBuPw+5PErrbH0INdfJOjwraO5sITaK12WMNdPMOksVkI+TdNwfAEzLWPyzP4FqmgHJ9zAAwslvRy/0z1UO3FEey/R0nA1r7nx+EHmii/rRp4mOarMUwl7/grFCquIZRAecbRXN68qKxeeZErD4GpLnXLWiFFWOYhc3z0hLoj7mns22rmOCx/jHl/vss/u7o77arjH6johvDTRfMrGZFGCgD3OrYh7YxZtdhYUEqgaUAoSbM1xH+fQE2uZ70Xozc3OOxsl6p1sNQlohIBHkeVvZqUFpx5LAf6osd+wes/Umc6mic6xRe229AfsfRNCe20o+fV9xcs1IxVObKkAkt3OOaq5jMyPBPzZvW0mjigllakYj/cM72I3yKk9ezFHzSbgfaWMP+z8c1B0YqeMZiaZT64HlN6lmLyABfFQmja5QsKUmwkQuryaWRPoU1rkMJkq7wp12ioUem49UhCZRnaKVd2qN2p29l3TGJbEDxlNeiLbdRyoxGJ9gy/WT/TvhHfHt6/JZwWt91Wqh8RMVkkQ7UmkajZq/TeOGdOawfAxfBJQZ4b5ZGCuRzazmd2+/15nm1udpxwXoGVfNpOHHTXYXPh0B7e0nxxretT6jw57h/OjxcK+0LXqLNp143mgv70jMyF89QC2xt9rCK9ECEEkx+S4FmG6VY/qvBkLI2NRPYwCZJa3W8T2UeTynHZSZQI8tinnACdjOQZf2jIeCraRvqJDPnW9nyUhimczNiu8huhy08VFtuw121xc7Ndpct7T0mZXQLetl6euVwFZ+mQZy6m/XTNTbstAQdU3ukuZ8yX89HRFf74SwYHL9nyrnOP6ulw4ruiGHJL+LcSkMxRcUI6rN/GU9KeTelxW1bJxDqeBQE7olhtPSH+2tCSyuHufvTl6q1EVFtSr7zyLr6ULaCQiCZLp4wXEfSPQP3j+Y6CZcFDMBoNAM4s5PWul0S7KWvEMiZXaPJIIsQsdGzoudDCJlSAvcvUyNY/7JvQKKTn1r56WPRb6Cj5KiEMVodaJVQd2DoveunQOIYndy++IT8rCRAkWP+EBdaZtjMY2lVDETuxr4ws6uxfEA7n+QavNRuMBht0jZfNXoOrUG1ZYXBA0iKCTntXao0DhKTpBsrf/wFMpvDQwXX/jD5d0jCL1RaDAdwAAD5HfmTQaNA4R6xgN8WWIT0L4EQvEZRCFsaoRrh5/fZU1Ml0WusGfarJmx2T9NWW+HyCUq7XuIJKM7i+Sa0a/yypsgRMn9PgmGtwfnDcRCt7d5pnp2n0lhjFjxuYEjlSPgi8EnBAJOgSyeBw/ie9qu5rkHw9D+3Zb+FuJmNd5+1FfgUAo11yji1Fv4Fw1Ee+iIOE/8r0pCEcJL05XD/xJru4a4R9b0jzyybkRXRAPex8bF537zSnw8yIbqSvszIXpX5YHacnLYv2Anxsp4w5U4BXwa2JIZ9SRG8Dz4kOZ84LuSLocQTfBs7/YzpZ2PrXiY7gdufth0S6z4PGwFXuQvNrS5lYUqbTLPvp1VU7fykyZQGVviHyMhMZpNgdyXSOCAJ4zMpHYP6JuOUbGcDMcRIXHHtEe6Ova6y6kwA12gnTfQvuL8bMSdbaatgHqqp4dHvQp0qxJa/VD6eIl+HuwS8avbzzSfi6HAB2LwZGd9CTbjveEeQIGWsGq0TE3/sZfedeLoVteqZsB2VPVEFIE3WbrPEpZrBz3WxN3q+4rWGCOa0e/8AwrIptYThnxmZrlYfEWCj3zgWgvX8o7i27qpl6sUQaKNk2rU4WjNxmRFhT8E/aWCUm3yQ/v9BK8U/95qdkgPsyXp+4QlIDcMAwNwxhk21NzIpVW+OJ/xt25ofmUr+2OXUPqy5/5DoPuQ2Onsb+PqYdo8jZx9F4c8TCzitTt9IKgFif+Nv/OUu0CvM/BuXgNgvPSQ4igmPQ/Whjfa5MPxTvRZF7F2a6hZsdBrpzQh/B4Gbcg06gFfocX1YKJQrA5dqqem3sQLRRbwrwSEl0ytAWWANh6Mb553owV3ggieSOl8uI3skFVwJNxawAmjx0UYonQ29KNRwcYZUFg+szshTyVZfqS5ZuB1dKT2LknEz3FDY9/clSX3mVbrzE21jmoTok4pLiyLLPOUna2Ps4Ep53AMMvsUTFJgU/cAq36zciJx8p4wsbGgLq5I2aD0S/Fqd/c5gcLkP9DtnAUu0RDeiT7U6uMIPcJu1IMt+L1gML7Y2P4DydQUdaYbbokJaXHmVizazTkS1HriQYP3toBiwEkzTA9d5QYxZuGD4f8V880aaJ5SnHCpjAHp/dJ8XRwBJQvW39nboedYfkTOOGe1wW76BeCJQAsF3C7GHBjQ7JEV9crVGUOi3iw5Chk6xPJymLnoDXI+ZuPBdKGBWfogOy3fFBby9p0491wFuxzPB3VcQeL67QpI5erSDUwgnltnD1aL9vWcuWUrj2UTjM3guN3zAllIVHwRDSA3IS/+1NB3A/TZJyjSNsbfmWvianBKnTCzxrqEgT6rKr5OtlLiVQ0VJ7bFRQqFasdcVZc99p3380vwcepjpe/oY/zVtmEAQBZg6qiPZWBiJglaIoz1tTFCNvfhRUHwB1uKZI2Hhx4D2uVO/HcbQnpOxz9EMgRUvRIV6jRXHrf5on2ZjUMQNAzHbRVsphNSoql/jy36rJo3iMxvg7dYmy8GW+Fqb+gJY8YSzRDLWPqNkBncO0AvgdnR8XZ32ryDFY4v8Hx6yXjhyPcqvp2DMJYgUvBoAPot40spV9VoxSyz/JmsWOJKRoKi6CmDjpoWL7/RsUlkREjOsTh74/HjxjA/CgWDhnXNNqqBvxE0QPtaKDaoo2HGgkgCuNkTI8jFYlRdszA4qtINAWba6ciN+CeYJrKBuXVDz9GYYOXKX6zxFaPX+kbBItQf7XRkJlfkHTxGZ+Gbg+5AkA9l76mWDjlmEWiqrCk/Ccj1/G7kiLSEpqe1grW9kBX9W2PjnBF+TmWptcGJuXQjjeks0DK6d6UUa1BAsYUcmPit0Jesd1rVZIMso7L0+bcHgiVYVbPYEld0zpkwYG4IlB/AxgCgLdbUYmtJ8/9z/kdrjLTglsEiFh+vGpcDWv1ymQvFhfzprJr2WHo+pUmJcarRATMlrF8PinJYzPv2KadyYhJt3Pj8Qdl47fl79HkiCbONG3hu94rrO6hl8qi9a+uK5U2JieHh1h4rV5XN8RCEqToqU6IE6d6GfOj6lAGTDjfELdeFiA/UciPg4rRJuqCh5jOLL+nmk33hNIK5HgivVO1IKSqOuiV6GjLd2BxtM47Q1P/b05fdcNWbrm4/u8PeH0HfHgAfpja+cSsi2VqnmPMYK8GearhqzGPBtQ0cWPNnBzgTQcxMYEj2SQUXLe+7usW/gGhAmlCwU3CXIaYdRE47wswSlZrNESgjBYhHgzEIt3Y0ANXCIwDVJmo5/WDzVTpUmOQHRr1VHAPbL6YkTRvVZ/A8WfafRtGoV8GC9VpblyG9LYplDbxYOEPXd2xxUEJo8V1IdHuySZZc9sjQssZq0CwYwIeaGhBTfMPlpODpC4Ss8Junh3Un1kyW3lIeWafe7H/kTlrZl+sWcmTV9w/B8WyPNQrgjiq8iqxIOeSafL6QKT4YTJTEqW6WWshmzWc4j0/0KiPyxe8g4Wh+p7w0gZGvG4yhB8D6PkT1rr2SvgrNwC1bNZP4znJH8laK33b6XiERmXOp0/71rscINjb40yZvolQWkHCftvrhQWcnX5JB5XmNEEE2BMMLezfKL+JHJJqLPljf9EDL4bkpG9McWaLQJmXQSui6/BzCIDQW+j5qc7DPF0gGDvSG8+ks4TWsDlQeW3QX4Zw7XHSxC/E7OShabLJHVLCCseXh2J0vSKBwxaTqHsDAob/kU18c55mfgzCPXw9o3nETImJghLQ7UmfNCtg6xeS5yrfqRPwCknohdKpGWPR44N/5UsO0mSYOMQQvrm3/84uVx7LEGLvC8uvNcRPLckjfon+lCpXgH/dl0B+RUyxsc56o3bemb6QGLC7mUQl1tDd7lIqCxAiMCy9dIimjuj0UQptI1RPKcgWJDQkoheNJQjX0NtKPGLVvmSFYqZ0ZjR7licEuf00yhbUp0X2uYpJaOjqiUIHYEKDtGG+xqKgXw4riaguZ8gjEzjKyvOPimOL2LGckryrNrWxeoks2EbarFYNnKso0aKPSDKbdk2bJSK6a9IxQrzUts5tCI9NhBFIglqVlq4AMZ3EpC//qO57N3GIILmXFrS7msLtNE7jaBSsTWX/A6JW5/KfQghd7rnSeI377pWaWVKrHsgemfQoyAQNjb3aBmHxcYVpm/ohZ2UNfS1QZ/hmX9QNqxJD8v9k4XRlwXvNWkQuc/FIYB8MYVCjehHw8nC6stipYjunKpyyzZNbuYCnYdIw6Zr8BMC7z4vL/FCzvPaxQUppaCCxK94tezDJHgwI8QlHFCgE6PyC4bBXG17y11+fDEOAZtR/rSA8JgOBnQpqNmSnDW7tzISB50t5U8VYOO3iJEhYcpy7I8WXBqO5uyyVYstzdv0g+miwdOd2XYgbBoOK6DgL5kCft5JxCG1X+MauL23ceUj2LZj+vN1yOMvLmaru36uIwl7kRLivTAbwkJ4P/FsOIn5dOt3uaHaPjeJ2CthPP1d2CGWctE8ItNikVJ0fmsB6HPk6S5YngtnVNI6mOreExJms6j3XYXCjLpzW07SSm5zVyeR8r7aZ78FoViSLqxVsWmEUt2kNhhEtycb6l7Rp/ofjzTTR7SI5VvgRv/lOTzxlkFVX5x+zJZk6HSKJKgfqRljfXGmIUXtBjXpP5uMup9Hvjx5lJsIipQhTjS/EVV4PNTUQWoEeN2zy/0KWsp+FVqy3VeqoexWTc56Jf1/mXxFbT8JrLRigrY56QZSvgDp+tJ+sfRwog==}"
              scope: GLOBAL
              username: "git"
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: false
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  defaultFolderConfiguration:
    healthMetrics:
      - worstChildHealthMetric:
          recursive: true
  extendedEmailPublisher:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: 0
    precedenceBulk: false
    useSsl: false
    watchingEnabled: false
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:8080/github-webhook/"
  gitSCM:
    createAccountBasedOnEmail: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  location:
    adminAddress: "Endereço ainda não configurado <nobody@nowhere>"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  timestamperConfig:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
