credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              id: "39c19e12-311b-4dd8-b402-a2c3f062ee5e"
              privateKeySource:
                directEntry:
                  privateKey: "{AQAAABAAAAywUumPh86AzcKcU2f0yKci1IsoqPvWfZzA8QsONF88YUjWDAXoAOtUr95AZsf6A1lVrApb1Hd6QlWbGqpNmUSpMnSuhYsU7WRg3oHbtGg+JrZgddoqrrmSshHjZd0C2eeEcS/en0WbH409RodaJ089o13MA55cIfgl2tvOEdI2d8FN5opVv7MSSy05eG0jLp3jLlsgvIBIaeJqMT2vWoDPj17y6nNRuDV0sMYHijhg70OMNjaxQc5czB83v/Ze9+nFBMm/VSSkrMr93gr02n7sFXYw6lHu8JSOt3Q91TuuPL+ww+fkeWdarAvH/1tFPtW8l8fg+WuJ8F0k8ywyuFntNBPlVsviBUNf3ZbAMrjq8pvKJ0Y7zaKUVMfIHAAd0sq4HyaVXhxOZTR4yIEuiZ99TzQsRtm0pPHQdMrMs3DjbKqePo5N3/sDmygQ8M/Hd0lXUA29H5zn9peJU6cBL8PY8EzqtQtaOt0Cpl7VlUa5kpMkKNltFqNO1h5B3JNqVMz9E9WFbEHcJcZ6gv28OEVmNINkkBjY1HiBIXv/n2SkH78EtNqBNFh6znkl83kvmrCnNOctwgxU1CaraSXMhHK+7MjAzcGeePqmCsC5bxXZrXA5zP/uXPY6lq24j5e3XbaHL3ncdjZskvEoQ4wZos5Q+MTPTil+unwWYAjLXOSkrgE+tAEqV9AYY78NNCDABQ3FUcLNrxV/AU1fxRXuffvfpSlO/qFYQv5Jeplxi/foAMrq9/991lj4KIv6pvKigiFmSPNDPlIHJI7fCMoLrzBuRz79g7ODjqqbzeSl3qsHZ0cO5NarDaXZXDxSXK4DjhbvkVz0jqA54K4P7gLymE5A8+vSa3J49ZQgfl99kddW0UQLWikne6gybLyfX/MRhvVHoT9o91ELvVExOGxrRXzuYdN3pvMh8lojOTYEyPpTQJbGqePPiPaHVYerOcBZnbTeg5eZYkbdUn4FZLSyyLN7oE/9f3pDw8o6PQLqfzPn+fNA9LHF7VAD/MQQ2s95+COhtR6+OW+SZsP6UkGb7nL2DwZonXiSgOsm/qMQ2+5v15e0d7fqMlfdsuUsToXjxjFdGEfuxeDweEn8H++Z529tjvpZRKEr6pliFVxM6a87zaG8Z00zfn9gb/c7GLI2g68FGzKrsYdlwdPRu7LNWK+zPnqrbJ/a9WqXX3K5zhSnrAGC+1nQEMidhhXwWAXETnseaj3zgnvsV2cxvzYHtb0HzkhvTDFZ0gAX2gB3ZLoLyoPly2l4ZhW4lZHdhYIcs1U0nEYbNTYc6njEUR2rU3HQKIjFfxau83sLO1Pqg7BUmTTu+cON0+hVXmCMgbM9hXujJD075STNvp7FnhN4qu4RW2QmxDAN8MyLn4uiAjUkbWRns/noCahARZjX10TnIZDBCy11EEBWqoaikmY+TKqh2o+CmfB8DYsWjers7ZIhmyvmKbk7zYaynI22WrihOBeiKjJYv8CkyPMDCkm4rKAjg2oqdtf4ZYc7q69JKsQ4uEHSYI30qYVGRax7EbtfXjzLVc1LUwn/4jE6qoSQwK65orYYGXSGa2Va/GmDZ0cvc7FfSy/g/KiKtZ3dRDsEp52Qp3c0hq5fuusFPF+W3UIpebAhFRgLUF1I0bNy4xsXljP2EnmHaDVlubKchzLigIFf7zvebOQMG5iuUCDLLqhu4h83cgu6bXKi1iht5PjWzm0Vco7aSGFu/CK0CFlGBJ4OVRsT62hR5+VfH2DYBXrBzdIodOfHjSErYJn80pYdXo784zYPy5UMwqO/ZWP/m8naq6jm1M6PUUvJrSe5oatuTbjQ3yEYzEZkKiPbdCoDuoecE92hyKxDcbZSt6/9Yt3tzTZIOeB2Ku78ZnrTZVWwVeDMYMBHFxY1gua/74ZvrxC1caPQzHV4UwWjoty7hZzAkNzuc6qFDjGGFusIA+E09vmeLfzg3R1GalTFu/oER9Db1MUcEUA2DsxL6h2YtHPOgzFCfSfUsVbzpsKRKc7bLYlPysGVHw6iR8GNBrQ1P9g7CbZb5f52jFBJuluJvwXi1TBmtmIxxJXRu9dBk1gbMuatLC1OAsx4QVLduSYpeodfwX5s2r3Ba1gKDzlqWRelmZJWOplG7zqO7yDay/tfeTBLePx+GbqvzM2kHvKprEdzv1bFLxQTvIkCjn8NGK2HY20WmlwxYJV5u5dwpP8jLocJLCPsjiNogbItdi+Nt56UzsWno20Wgz1ikUcTvHcsAD0GqWF6tPslmwSMr9suHGKhCkrzmYX039hYLaV2Bhmvt6mJo1JP2Kh+GPNrt91116Wmv66p4iNnxc3o2BqWnLOIs8/B/sRH4TgWGgj3O+P4KjnKSUuoCnleIMWk+RzTNK9eSBv+L7w2k79FhY+si2eu0MAgm95vPc9sBUEaKLv/EmSdMk3LRc+hKQOS7EqUzcHRQqPbcffFvJNV7/ipykk1phYzRKnaxRUs08Sc1AZWh0qg2G/w//uYbZyfUB84BdQoly458eXiJNynVwPdrnNuxKBcA/tAD2E2E+nGC8mFV35Q0MZx4ABCqXjxP5ggQRMahIz8w/Qu+M5UssYOIb/gcYR4NWKYxd7cbuK/nAOU2bdmASeHGvZk+xaU4xxf1wbW/zJcRSgQgYlLPi9zYqG9iXe4phNNXFrFMEybHRtydiOe1bYAGP5WE4P/qfTpZqPWUfSOV3gMQ4BWwOmKRmYfHdmgAjzRdXQ+BFiSBdx3EEZ+dj+33EsbGkCf47O2XkqUgzvkyqMzxDLgPisUpzSmcZKX/bqJqyxW0k3PSsAo6sewfjZxoDKR0jXU/sZ0MVRaFhjgUZD+eIz/W12v70gQSUTEGq6roJFPiabDS+/0sKvN+BCy+2xymIYFyIjlRmsI7gLqKLcjcHtRgQJ1K2Yhc9RM+ZdOGd2zqELwn6pP8vzwJDeCXX5/8qRb4BzpwWWTeYdOb9aLu7UUHcRQAMffLZv67T7MfDZQKd3ULHr8XP7/CMFc/0L17CpWrzwWzifs2ImiJIJxbvlZ5r99TzEruc+O2Wm0S8YeEkByyhoFgKOmr1gcbHEEmBEJgzGJQeKxmKUlvqRRGhbk7Y2BcmrMpSkjd7HlXgFPiWIQYEJfW80DRuXrWcOTJcFjWjC1b8Ycpwhk16RxbOoI/+/emZ6mEG1NK6aRaHn+rs1scBea4P3aX8S1y+qleLN3D/OhLUJjXQJK92dX+qTi3gbdYOOxAGTy2/dGDdAKHgnPa5YxoMkMqvknvihB5AQntuUzI9Swjj5f2qFwoWYeN+kknOoERVaiTVaHZZklq3NLcnAUQtZQhED655Jhbf/vGSzLCFixgW3dbEqHg5fxiaLkZydYHIVmI+42QFtZulX45QD8hteApKhov4axdHoQS/VFs7Vsvw9kWRio5D6KGogx45yOt3aCXBIDVln2V/MVPieFSTSujjQYV4ytm3vFPTl3wKmfEDRnDw5RIRxqHbEK1wvyFC86kXdQ9OHeor+n4ODmRXUJLzA8CbYi+HLaSOijtrs/5RfDlvWzCeRYrLHe5PLQR85hnIgLOnkcHwxE9ArcPhGMsCvNf6taCR14GgELWp5cgY8NJnlrFO4+a51HbMqHd52bU4MuE+z4TUTuu1xu9WKXcOiTLrTMjEfLVLI2jlDgPW2VyPmTqsUEI+cKxSuvXKohnM8WFhmRKya/RUV5sXNUBHkiMbnqPyVYTEI4UyJnQE1Q4ouHtz46PXVN/+Sj68QCQshGw0U/rr16EUTtlC868DDVHSgtXNWm4ZtA0v6/rTh9Z6OyAbHMcJySbPcoj1XUVTGThToH2j4MonqKlU2NsMHqqnp8G95wHTKM6mjXPbgzt46Vxl4SFedF8K947a0zHC+aws3xeQatLgGPQV0aW7EQydIo6Q7E6sgIAbfFmeE+/KsFU6XlDWJy0ayB3fR6ky8c5XaEyW7MmouBvpvsMvv5S8uQq+swsO4G5gVQTt04mXFDzVBON+IqQ9LSr3VUd+OYRS7TZp+dTZnysxDQTHusEZnxzmWB3KYyrqF6wRM8QYjZABtC6JiPdeyQj1xSyxN3TuBGBL6lEBgLj5uyhi8on1eDeneybN0rwflWFLX5NhwAUUc2+UEpV68F4ETODJkNbYPFxbJHkt71DxKUHEd4+KIhkTIy21dxxKcB4UGVKnksu2p3BYqAwznh4Vc9vtgtLJoj8QJKSLAt5jYB2vUjfgn0xfNEkkldl8Ja1EhdqGLlmyG0omKOgg7RHX467LbsiOWsZdTioPWB1VfmSlWFwJXNt6qsnP8sdfZq/iOebtIaI/kPOhRR2NUD88vDpAXSlc79O5zP33Dp4pK0NDiXHf99TKOl63dX}"
              scope: GLOBAL
              username: "git"
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: false
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  defaultFolderConfiguration:
    healthMetrics:
      - worstChildHealthMetric:
          recursive: true
  extendedEmailPublisher:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: 0
    precedenceBulk: false
    useSsl: false
    watchingEnabled: false
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:8080/github-webhook/"
  gitSCM:
    createAccountBasedOnEmail: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  location:
    adminAddress: "Endereço ainda não configurado <nobody@nowhere>"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  timestamperConfig:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
